#!/bin/bash

# My way to configure NordVPN client nice, quick and easy
# It'll make sure to install wireguard-tools, an unmentioned dependency
# and add user to nordvpn group

clear &&
sleep 1 &&
nordvpn set tray enabled &&
nordvpn set analytics disable &&
nordvpn set autoconnect on se &&
nordvpn whitelist add subnet 192.168.1.0/24 &&
nordvpn whitelist add port 137 &&
nordvpn whitelist add port 138 &&
nordvpn whitelist add port 139 &&
nordvpn whitelist add port 445 &&
nordvpn c se &&
nordvpn status