#!/bin/bash

# My way to configure NordVPN client nice, quick and easy
# We utilize NordVPN's built in function 'whitelist' and allows Samba and
# LAN during the entire VPN session using connmark and iptables. 
# jontas@gmx.com in 2023

clear &&
sleep 1 &&
nordvpn set tray enabled &&
nordvpn set analytics disable &&
nordvpn set autoconnect on se &&
nordvpn whitelist add subnet 192.168.1.0/24 &&
nordvpn whitelist add port 137 &&
nordvpn whitelist add port 138 &&
nordvpn whitelist add port 139 &&
nordvpn whitelist add port 445 &&
nordvpn c se &&
nordvpn status